/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IEchoholders__factory } from "./IEchoholders__factory";
export { SimpleAirdropDAO2__factory } from "./SimpleAirdropDAO2__factory";
