/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAirdropClaim } from "./IAirdropClaim";
export type { MerkleTreeTHENFT } from "./MerkleTreeTHENFT";
