import RewardsLayout from "@/app/rewards/RewardsLayout";
import {Metadata} from "next";
import dynamic from "next/dynamic";

const NoSSRRewards = dynamic(() => import("@/views/Rewards"), {ssr: false})

export const metadata: Metadata = {
    title: 'Rewards',
    description: 'Generated by create next app',
}
export default function Home() {
    return (
        <RewardsLayout>
            <NoSSRRewards/>
        </RewardsLayout>
    )
}
