/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as epochNftSplitManagerSol from "./EpochNFTSplitManager.sol";
export type { epochNftSplitManagerSol };
import type * as nftSplitAutomationSol from "./NFTSplitAutomation.sol";
export type { nftSplitAutomationSol };
export type { AutomationBase } from "./AutomationBase";
export type { AutomationCompatible } from "./AutomationCompatible";
export type { AutomationCompatibleInterface } from "./AutomationCompatibleInterface";
export type { EpochController } from "./EpochController";
