version: '3'
services:
  app:
    build:
      context: ../  # Adjust the context to the root of your project
      dockerfile: docker/Dockerfile  # Specify the path to the Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Specify the path to the NGINX config file
