/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IEchoholders } from "./IEchoholders";
export type { SimpleAirdropDAO } from "./SimpleAirdropDAO";
