/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IGaugeFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createGauge" | "createGaugeV2"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createGauge",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      boolean,
      AddressLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createGaugeV2",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      boolean
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createGauge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createGaugeV2",
    data: BytesLike
  ): Result;
}

export interface IGaugeFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IGaugeFactory;
  waitForDeployment(): Promise<this>;

  interface: IGaugeFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createGauge: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: AddressLike,
      arg3: AddressLike,
      arg4: boolean,
      arg5: AddressLike[]
    ],
    [string],
    "nonpayable"
  >;

  createGaugeV2: TypedContractMethod<
    [
      _rewardToken: AddressLike,
      _ve: AddressLike,
      _token: AddressLike,
      _distribution: AddressLike,
      _internal_bribe: AddressLike,
      _external_bribe: AddressLike,
      _isPair: boolean
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createGauge"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: AddressLike,
      arg3: AddressLike,
      arg4: boolean,
      arg5: AddressLike[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createGaugeV2"
  ): TypedContractMethod<
    [
      _rewardToken: AddressLike,
      _ve: AddressLike,
      _token: AddressLike,
      _distribution: AddressLike,
      _internal_bribe: AddressLike,
      _external_bribe: AddressLike,
      _isPair: boolean
    ],
    [string],
    "nonpayable"
  >;

  filters: {};
}
