/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iGaugeFactoryV2Sol from "./IGaugeFactoryV2.sol";
export type { iGaugeFactoryV2Sol };
export type { IBribe } from "./IBribe";
export type { IBribeAPI } from "./IBribeAPI";
export type { IBribeDistribution } from "./IBribeDistribution";
export type { IBribeFactory } from "./IBribeFactory";
export type { IBribeFull } from "./IBribeFull";
export type { IDibs } from "./IDibs";
export type { IERC20 } from "./IERC20";
export type { IEcho } from "./IEcho";
export type { IGauge } from "./IGauge";
export type { IGaugeAPI } from "./IGaugeAPI";
export type { IGaugeDistribution } from "./IGaugeDistribution";
export type { IGaugeFactory } from "./IGaugeFactory";
export type { IMasterchef } from "./IMasterchef";
export type { IMinter } from "./IMinter";
export type { IPair } from "./IPair";
export type { IPairCallee } from "./IPairCallee";
export type { IPairFactory } from "./IPairFactory";
export type { IRewardsDistributor } from "./IRewardsDistributor";
export type { IRouter } from "./IRouter";
export type { IRouter01 } from "./IRouter01";
export type { IUniswapRouterETH } from "./IUniswapRouterETH";
export type { IUniswapV2Pair } from "./IUniswapV2Pair";
export type { IVeArtProxy } from "./IVeArtProxy";
export type { IVoter } from "./IVoter";
export type { IVotingEscrow } from "./IVotingEscrow";
export type { IWETH } from "./IWETH";
export type { IWrappedBribeFactory } from "./IWrappedBribeFactory";
