/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as merkleTreeThenftTestSol from "./MerkleTreeTHENFTTest.sol";
export type { merkleTreeThenftTestSol };
import type * as merkleTreeTestSol from "./MerkleTreeTest.sol";
export type { merkleTreeTestSol };
export type { AirdropClaimTest } from "./AirdropClaimTest";
export type { AirdropClaimTheNFTTest } from "./AirdropClaimTheNFTTest";
export type { ERC20Token } from "./ERC20Token";
export type { TWBNB } from "./TWBNB";
