/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INFTSalesSplitter } from "./INFTSalesSplitter";
export type { NFTSplitAutomation } from "./NFTSplitAutomation";
