/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BribeFactoryV2__factory } from "./BribeFactoryV2__factory";
export { IBribe__factory } from "./IBribe__factory";
