/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWrappedBribeFactory,
  IWrappedBribeFactoryInterface,
} from "../../../contracts/interfaces/IWrappedBribeFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "existing_bribe",
        type: "address",
      },
    ],
    name: "createBribe",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_external_bribe_addr",
        type: "address",
      },
    ],
    name: "oldBribeToNew",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "voter",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWrappedBribeFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IWrappedBribeFactoryInterface {
    return new Interface(_abi) as IWrappedBribeFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWrappedBribeFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IWrappedBribeFactory;
  }
}
