/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20Ext,
  IERC20ExtInterface,
} from "../../../contracts/Bribes.sol/IERC20Ext";

const _abi = [
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20Ext__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20ExtInterface {
    return new Interface(_abi) as IERC20ExtInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC20Ext {
    return new Contract(address, _abi, runner) as unknown as IERC20Ext;
  }
}
