import React from 'react';
import {Metadata} from "next";
import LockLayout from "@/app/lock/LockLayout";
import dynamic from "next/dynamic";

const NoSSRLock = dynamic(() => import("@/views/Lock"), {ssr: false})


export const metadata: Metadata = {
    title: 'Lock',
    description: 'Generated by create next app',
}

const Page = () => {
    return (
        <LockLayout>
            <NoSSRLock/>
        </LockLayout>
    );
};

export default Page;