/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as merkleTreeSol from "./MerkleTree.sol";
export type { merkleTreeSol };
import type * as merkleTreeC98Sol from "./MerkleTreeC98.sol";
export type { merkleTreeC98Sol };
import type * as merkleTreeThenftSol from "./MerkleTreeTHENFT.sol";
export type { merkleTreeThenftSol };
export type { AirdropClaim } from "./AirdropClaim";
export type { AirdropClaimTheNFT } from "./AirdropClaimTheNFT";
